# Generated by Django 3.1.4 on 2020-12-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/%d', verbose_name='Project Image')),
                ('title', models.CharField(max_length=100, verbose_name='Project Title')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_html', models.CharField(max_length=100, verbose_name='Icon HTML')),
                ('text', models.CharField(max_length=100, verbose_name='Skill Name')),
            ],
        ),
    ]
