# Generated by Django 3.1.4 on 2020-12-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='resume/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='proj_url',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='text',
            new_name='skill_name',
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='Github URL'),
        ),
    ]
