# Generated by Django 3.1.4 on 2020-12-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201229_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon_html',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon HTML'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill Name'),
        ),
    ]
